export enum PurchaseStatus{
    CREATED = 'CREATED',
    MODIFIED = 'MODIFIED',
    PENDING_APPROVAL = 'PENDING_APPROVAL',
    IN_PROCESS = 'IN_PROCESS',
    PROCESSED = 'PROCESSED',
    REJECTED = 'REJECTED',
    CANCELED = 'CANCELED'
}